import React from 'react';

function SamplesPreview() {
  return (
    <div>
      <h1>Worksheet Samples</h1>
      <p>This page will show preview samples of worksheets generated by EdNet.</p>
    </div>
  );
}

export default SamplesPreview;

